services:

  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 6000:80
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ngfz2rmj
      MYSQL_DATABASE: health-insurance
    ports:
    - 6001:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 6002:80
    environment:
      - PMA_ARBITRARY=1

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
    ports:
      - 6003:8080