services:

  health-insurance:
    container_name: health-insurance
    build: .
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 9010:80
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ngfz2rmj
      MYSQL_DATABASE: health-insurance
    ports:
    - 9011:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9012:80
    environment:
      - PMA_ARBITRARY=1

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
    ports:
      - 9013:8080